### ISSUE TITLE
random NoHostAvailableException on startup

### ISSUE THREAD

**Issue by depend** [jsevellec/cassandra-unit#154]
It's similar to https://groups.google.com/forum/#!topic/cassandra-unit-users/ttVeJAyq6KY
For any given test it has 50% chance to fail on startup. Then it's OK if I rerun it. For a project with a few tests it's almost impossible to get a clean run.

**Comment by depend** [comment]
This happens when EmbeddedCassandra starts too often. So instead of starting an instance per test, I now start the EmbeddedCassandra instance per suite. This helps a lot. Now I rarely see this error.

**Comment by wakingrufus** [comment]
@depend How do you go about doing this?

**Comment by soid** [comment]
I start EmbeddedCassandra once per build and still see the exception every few runs.

**Comment by paouelle** [comment]
I also see this often. I suspect that when we run a multitude of test cases, this puts a lot of load on the memtable, commit log, and sstables.

I wonder if there would be a way to force a flush and compaction after each test cases. That way, the next test cases that starts wouldn't see impact caused by an unusual set of cassandra operations.

**Comment by depend** [comment]
Close since it happens so rarely now that it doesn't bother me.

**Comment by soid** [comment]
I think it's intermittent. For some people it's more often, for some people it's rare. 
It sounds like the "works on my machine" meme when you're closing this ticket.

![defect-in-production-works-on-my-machine](https://cloud.githubusercontent.com/assets/213141/20329419/dd34dd4e-ab4c-11e6-924b-5cb7cdeacd70.jpg)
